"""Generate FINDINGS.csv (kept as a script so the quoting is exact)."""
import csv, sys

C = "4ed66de4e2f3161464b9205583b3ee7a97133904"
HEAD = ["ID", "severity", "status", "new_reopened_inherited", "area", "invariant_violated", "architecture_citation",
        "affected_commit", "code_location", "reproduction", "observed", "expected", "restart_replay_consequence",
        "security_failopen_consequence", "determinism", "recommended_remediation_boundary", "required_regression"]
ROWS = [
 ["RA6-001", "MEDIUM", "OPEN", "new (introduced by R6's acq_derivation_rejected verdict)", "RA5-001 durable terminality / HA-04 settlement",
  "Every failure path writes a durable coverage/exclusion record, and a restart completes any verdict side effect a crash cut short (R6 claim: reject_derivation is 'idempotent across a crash at every write ... after it, settle_last completes the coverage entry')",
  "15 D13; 11.1; 14.4; HA-04 (settle_last)", C,
  "adapters/src/genesis_adapters/oddspapi/acquisition.py:967-975 (settle_last settles only the newest PLANNED attempt), :1050-1065 (reject_derivation: row, then settle(aid)); pipeline.py:178-202 (resume derives OLDER captures in ledger order); cli.py:_run (G2 = raw only; the first G2R start resumes every G2 capture)",
  "probes/a01_settle_gap.py: G2-style runner.acquire of a poisoned ODDS body (fixtureId outside the grammar -> terminal derivation rejection) then of a healthy body; first G2R-style start = reopen + resume() with a crash injected at the runner checkpoint 'after_derivation_rejected'; restart; resume x2. CONTROL: same crash when the poisoned capture is the newest attempt. evidence/a01_settle_gap.txt",
  "ATTACK: acq_derivation_rejected durable, state DERIVATION_REJECTED, pending_work() == (), and the REJECTED coverage entry is NEVER written (no later step looks for it). CONTROL: entry written by settle_last.",
  "After any restart the coverage entry gid('cov', acquisition_id, note=<failure>) exists exactly once for every acq_derivation_rejected row.",
  "Restart-stable but permanently incomplete: the attempt has no coverage record at all (its successful completion wrote none); nothing reports it, pending_work is empty, so the gap is silent. A persistent write error on the coverage append (e.g. ENOSPC right after the small ledger row succeeded) produces the same state without any crash.",
  "No unsafe datum and no wedge: the capture is (correctly) never derived. Audit-trail / D13 completeness defect in the BLOCKER's remediation mechanism; the root cause is that R6 creates the first verdict row that can be written for an attempt other than the newest one, breaking settle_last's assumption.",
  "100% deterministic with the checkpoint crash",
  "Make the restart path settle every acq_derivation_rejected row whose coverage entry is missing (the entry id is deterministic), or have settle_last scan all attempts with a verdict row after their last settlement; keep the fix inside acquisition/pipeline.",
  "Crash at 'after_derivation_rejected' for (a) the newest and (b) a non-newest attempt (G2 -> G2R flow), and a coverage-append OSError: after restart exactly one REJECTED coverage entry per rejection row."],
 ["RA6-002", "MEDIUM", "OPEN", "inherited (reproduces on b22263e for 'reported > debited'); broadened by R6 (RA5-011 makes every unreadable usage header take this path)", "C quota divergence / restart convergence",
  "F-37 quota divergence: 'Observation / head: none; halt', evidence retained 'acquisition + headers' (section 15 default: no usable observation); a restart converges to the durable outcome of an uninterrupted run (14.4, HA-04)",
  "15 F-37; 14.2 (halt all live acquisition; human review); 14.4; 15 D13", C,
  "adapters/src/genesis_adapters/oddspapi/acquisition.py:579-583 (verdict_effects: QUOTA_DIVERGENCE halt but completed.failure stays None), :852/:925 (AcquisitionHalt before normalize); derivation.py:50-58 (successful_capture ignores the divergence); pipeline.py:196-200 (resume derives it); cli.py:_run (rt.resume() runs at every G2R start, before any gate check)",
  "probes/q01_quota_divergence_restart.py for x-requests-used in {99999, 'not a number', 1e5, -5, 99,999, full-width digits, 300 digits}; same probe on the BASE tree. evidence/q01_quota_divergence_restart_R6.txt, _BASE.txt",
  "Uninterrupted: AcquisitionHalt(QUOTA_DIVERGENCE), 0 PIT records from the response, pending_work = 'a successful ODDS capture is not normalized yet', reader DATA_CAPABILITY_NOT_READY. After reopen + resume: the attempt is NORMALIZED, 12 OPEN documents from that response, reader returns UsableBook from it, while the QUOTA_DIVERGENCE halt is still in force. BASE: same for 99999; malformed values were accepted (no halt) and derived at once.",
  "The divergent response yields no usable observation in every run order (its completed verdict - or a terminal row - must make successful_capture false), or the architecture is amended by ADR to say F-37 keeps the response usable; either way the uninterrupted and restarted outcomes must be identical.",
  "Restart-dependent semantics: the same durable ledger yields 'no observation, reads refused' or 'usable observation' depending on whether a start ran resume(). Every G2R start derives it.",
  "Fail-open relative to the failure table: a response the architecture says yields no observation becomes decision-usable PAPER evidence while the budget is declared untrustworthy and a human review is pending. The response itself passed every content and secret check, so this is not a secret or quota breach.",
  "100%",
  "Record the divergence as the response's verdict (e.g. completed.failure = QUOTA_DIVERGENCE before the row is written, as HA-04 does for content checks) or add a terminal row that successful_capture honours; alternatively an ADR changing F-37. Inside acquisition/derivation only.",
  "For each usage form: uninterrupted and restarted runs give identical PIT/document sets (none), pending_work empty, reader never serves the response; mutant X39/X41 of this audit stay killed."],
 ["RA6-003", "LOW", "OPEN", "new (introduced by the RA5-003 fix)", "M TLS trust boundary",
  "Production TLS trust (and its protocol floor) is the platform's and nothing the environment adds, for every context the process builds; process-global state is not altered for other threads",
  "7.6 transport hygiene; D15", C,
  "adapters/src/genesis_adapters/oddspapi/transport_http.py:253-270 (tls_context: os.environ.pop of SSL_CERT_FILE/SSL_CERT_DIR/SSLKEYLOGFILE, ssl.create_default_context(), os.environ.update)",
  "probes/t01_tls_trust.py (restores the retired CA/leaf/key from b22263e history into scratch) then probes/t02_tls_env_race.py <cand> 300 on 3.11/3.12/3.13: SSL_CERT_FILE=<retired CA>, 4 threads x 300 tls_context() calls + an observer thread. evidence/t02_tls_env_race.txt",
  "Contexts trusting the retired CA: 9/1198 (3.11), 12/1197 (3.12), 12/1196 (3.13); KeyError raised out of tls_context() 2-4 times per run (check 'name in os.environ' then pop races); an unrelated thread saw SSL_CERT_FILE missing in ~95% of reads during construction. Single-threaded: never trusted (also verified with real handshakes in t01). Second facet (probes/t03_tls_floor.py, evidence/t03_tls_floor.txt): production never pins minimum_version; on the Ubuntu CPython 3.12.3 build the stock floor is MINIMUM_SUPPORTED, so an environment OPENSSL_CONF (MinProtocol = TLSv1, SECLEVEL=0) lowers the production floor to TLS 1.0 and a TLS 1.0-only server gets past negotiation (the certificate is still refused); 3.11/3.13 keep TLS 1.2.",
  "tls_context() never trusts an environment CA and never raises, whatever other threads do, and does not change what other threads see.",
  "n/a",
  "Latent trust redirection: only if two contexts are built concurrently in one process (the live runner builds one in one thread today); environment exposure to child processes/threads during the window. Not reachable through the current CLI.",
  "race: probabilistic (~1%), reproduced on every run",
  "Do not mutate os.environ: build SSLContext(PROTOCOL_TLS_CLIENT) and load the compiled-in OpenSSL defaults explicitly (ssl.get_default_verify_paths().openssl_cafile / openssl_capath, which ignore the environment) plus the Windows stores on Windows, set check_hostname/CERT_REQUIRED/keylog=None and a TLS 1.2 minimum explicitly; or at least serialise with a module lock and use pop(name, None).",
  "Concurrent tls_context() with SSL_CERT_FILE/SSL_CERT_DIR naming an attacker CA: zero trusting contexts and zero exceptions over N runs; os.environ untouched."],
 ["RA6-004", "LOW", "OPEN", "residual of RA5-004 (disclosed by the implementer as known risk; re-graded here with measurements)", "B hard deadline",
  "Hard transport deadline Tq + request_timeout_seconds for the whole attempt; at the deadline the attempt is aborted (writer and run lock released)",
  "14.6 rule 3; BND-04", C,
  "adapters/src/genesis_adapters/oddspapi/transport_http.py:148 (socket.getaddrinfo before any bounded operation)",
  "unshare -rmn python3.11 -B probes/r02_dns_stall.py <cand> 3 (isolated namespace, resolv.conf bind-mounted to a fake resolver on 127.0.0.1 that never answers; production _Connection resolving 'genesis-audit-stall.invalid'); R02_THREE_NAMESERVERS=1 for three nameservers. evidence/r02_dns_stall_*.txt",
  "D = 3 s: held 10.0 s (glibc defaults, 1 nameserver) and 28.0 s (3 nameservers), NO_RESPONSE/gaierror; a resolver answering after 4.5 s held 4.5 s. No request byte written late (T0 checked after connect).",
  "send() returns by deadline + small epsilon whatever the resolver does.",
  "None (the attempt is NO_RESPONSE; no orphan).",
  "Availability only: whoever slows resolution (the provider's authoritative DNS within the resolver's limits, an on-path attacker, a failing local resolver) holds the single writer and run lock tens of seconds past the deadline per attempt; accounting attribution unaffected.",
  "100% (timing-based, large margin)",
  "Bound resolution by the remaining time (resolve in a helper thread joined with the deadline and abandon it, or resolve once per run outside the attempt and connect to pinned addresses with hostname verification unchanged).",
  "Stalled-resolver test (namespace or injected resolver) asserting send() returns by deadline + epsilon."],
 ["RA6-005", "LOW", "OPEN", "inherited mechanism (any code_version/policy change), triggered by R6's mandatory new derivation source", "versioning / 13.3",
  "A derivation-source change is detected and handled explicitly (13.3: new source; the old source's capability BLOCKED at T_fix) and never reported as artifact tampering",
  "9.2; 13.3; 15 F-32 (EVIDENCE_CONFLICT means tampered/contradicting evidence)", C,
  "pipeline.py:192-195 (resume re-normalizes finished[-1] under the RUNNING derivation_version) -> emit.py:326-343 and :369-372 (_verify_complete finds no observation for the new version's artifacts) -> EVIDENCE_CONFLICT halt",
  "probes/v01_versioning_replay.py part C: a root written by the BASE code (24 PIT rows, mb1-5456effb3fe6701f) opened by R6 (mb1-eee12f31dd5c2597) and started twice. evidence/v01_versioning_replay.txt",
  "Every start: PipelineHalt(EVIDENCE_CONFLICT), a durable acq_halted EVIDENCE_CONFLICT row and a QUARANTINED (ARTIFACT_TAMPERED) coverage entry appended to the old root; reset cannot help (the next start halts again).",
  "An explicit refusal naming the derivation-source change (or the 13.3 procedure), no tamper-class verdict, no growth of halt rows per start.",
  "The old root is unusable under new code and accumulates false tamper verdicts; stale G2R pins are correctly refused (part B), so nothing is silently reused.",
  "Fail-closed (no data reuse); misclassification only.",
  "100%",
  "Compare the stored acq_normalized derivation_version with the running one at start and refuse (CONFIG_DIGEST_MISMATCH-class) or follow 13.3; document the operator procedure (new runtime root per derivation source) in the runbook.",
  "Start of R6 code on an R5 root: explicit refusal, no EVIDENCE_CONFLICT."],
 ["RA6-006", "INFO", "OPEN", "new", "RA5-001 / 13.3",
  "Re-deriving retained raw captures into a new derivation source is permitted and deterministic (13.3)", "13.3; PIT-09", C,
  "derivation.py:50-58 (successful_capture is false on ANY acq_derivation_rejected row); acquisition.py _ROW_KEYS derivation_version recorded but never consulted; pipeline.py:339 (rebuild_into skips it)",
  "code read + v01 part E (rebuild skips the rejected capture)",
  "A capture rejected under source N (including a DERIVATION_FAULT caused by a code defect, not by content) is excluded from every later source and from PIT-09, although its raw evidence is intact.",
  "Scope the terminal verdict to the derivation_version that produced it, or record why version-blindness is intended.",
  "Stable (by design).", "None (fail-closed).", "n/a", "ADR or version-scoped rejection.", "n/a"],
 ["RA6-007", "INFO", "OPEN", "new", "RA5-001 ledger replay",
  "Every durable row is replay-validated against the facts it depends on", "11.1; 14.4", C,
  "acquisition.py:346-356 (_apply acq_derivation_rejected)",
  "code read",
  "Replay checks state COMPLETED, T1 present and completed.failure None, the failure is some AdapterFailure and detail is text; it does not check role == ODDS, outcome RESPONSE / status 200 / raw id, nor the type of derivation_version, and accepts any AdapterFailure (e.g. SECRET_ECHO).",
  "Validate role/outcome/status/raw id and restrict failure to derivation outcomes.",
  "None observed (fixture_snapshot_for ignores the row for FIXTURES).", "A forged row can only deny a capture (never make one usable); the ledger is a hash chain, not a MAC, like every other row.", "n/a",
  "Tighten _apply.", "Replay refuses the row for a FIXTURES/META attempt and for a non-derivation failure code."],
 ["RA6-008", "INFO", "OPEN", "new (wording of the RA5-002 fix)", "A/B Date header",
  "R6: 'A Date that was sent but is unusable ... or dropped for length is a deterministic CLOCK_SKEW verdict'", "6.1; RFC 7231 (Date is a singleton field)", C,
  "raw_capture.py:186-194 (_allowlisted keeps the FIRST kept occurrence), :271-279 (_skew_failure judges values[0] only)",
  "probes/d01_date_totality.py part 2 (multiple-Date cases)",
  "[valid, garbage] and [valid, 99999999999-year] accepted; [over-long, valid] accepted (the dropped one is ignored because another Date was kept); [garbage, valid] -> CLOCK_SKEW.",
  "Either judge every Date occurrence (any unusable -> CLOCK_SKEW) or document first-wins.", "None.", "None (a provider that controls headers can send one good Date anyway).", "100%",
  "Document or tighten.", "n/a"],
 ["RA6-009", "INFO", "OPEN", "new", "Q test quality",
  "Every claimed crash-safety property has a crash-injection test", "19 GREEN criteria", C,
  "adapters/adapter_tests/test_v05_r6_poison_pill.py (no reference to 'after_derivation_rejected' anywhere in adapter_tests)",
  "grep -rn after_derivation_rejected adapters/adapter_tests -> nothing; RA6-001 reproduces while the whole suite is green (859 OK). (Mutant X18 of this audit is killed, but only through the no-crash path: test_a_rejection_is_a_durable_verdict_with_coverage_and_no_observation.)",
  "The rejection checkpoint exists in production code but no test crashes at it; RA6-001 went unnoticed.",
  "A crash test at the checkpoint for newest and older attempts.", "n/a", "n/a", "n/a", "Add tests (see RA6-001).", "Crash tests at after_derivation_rejected (newest and older attempt)."],
 ["RA6-010", "INFO", "OUT OF R6 SCOPE (frozen foundation)", "pre-existing in the frozen V0.4 tree (byte-identical at the freeze tag)", "frozen V0.4 risk-log integrity (F-3b)",
  "Concurrent writers through a toggled hard-link alias never land a row in the real risk log", "V0.4 foundation (frozen)", "frozen trees at 4ed66de = v0.4-foundation-freeze",
  "tests/test_astra_t6_risk_log_integrity.py:578-641 (src/genesis risk log)",
  "evidence/frozen_suite_py311.txt (first run, under audit load), evidence/frozen_t6_flake_characterization.txt, evidence/frozen_t6_contention_failure.log",
  "Quiet host: 10/10 pass. Under 4 CPU busy loops: 1/10 fails 'F-3b: the real risk log holds a row that was not written through its own name' (alias-0-12).",
  "0 failures under contention.", "n/a for the adapter.", "Possible TOCTOU in the frozen foundation's alias defence, or a timing-sensitive test; not decided here.", "probabilistic",
  "Foundation owners: investigate under the foundation reopen register (section 20); not an R6 remediation item.", "n/a"],
]
w = csv.writer(sys.stdout, quoting=csv.QUOTE_ALL, lineterminator="\n")
w.writerow(HEAD)
for r in ROWS:
    assert len(r) == len(HEAD), (r[0], len(r))
    w.writerow(r)
